sudo: false
addons:
  apt:
    packages:
      # Required headers to build against libfuse
      - libfuse-dev
      # necessary for kcov
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - libiberty-dev
      - binutils-dev
      - cmake
      - gcc

language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly 
  fast_finish: true

stages:
  - name: test
  - name: lint
  - name: coverage

install:
  - cargo install cargo-cache

before_script:
  - mv client_secret.travis.json client_secret.json

# Default script is the "test" stage
script: 
  - cargo build
  - cargo test

before_cache:
  - cargo cache --autoclean

jobs:
  include:
    - stage: lint
      rust: stable
      install:
        - rustup component add clippy
        - rustup component add rustfmt
      script:
        - cargo fmt --all -- --check
        - cargo clippy --all-targets --all-features -- -D warnings

    - stage: coverage
      if: os = linux
      sudo: true
      rust: stable
      env:
        - RUSTFLAGS="-C link-dead-code"
      install:
        - ./.travis/kcov.sh "v36" "29ccdde3bd44f14e0d7c88d709e1e5ff9b448e735538ae45ee08b73c19a2ea0b" && export PATH="kcov/usr/bin:${PATH}";
      script:
        - cargo test
        - for file in target/debug/photooxide-*[^\.d]; do
            mkdir -p "target/cov/$(basename ${file})";
            kcov --exclude-pattern='/.cargo,/usr/lib' --verify "target/cov/$(basename $file)" "${file}";
          done
        - bash <(curl -s https://codecov.io/bash) -F "${TRAVIS_RUST_VERSION}"

cache: cargo
