sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

# Required headers to build against libfuse
addons:
  apt:
    packages:
      - libfuse-dev

before_script:
  - rustup component add clippy-preview
script:
  # build
  - cargo build

  # test
  - cargo test

  # lint
  - cargo fmt --all -- --check
  - cargo clippy --all-targets --all-features -- -D warnings

cache: cargo
